"""second migration

Revision ID: 32fefa5b138e
Revises: ee2f4350b603
Create Date: 2025-05-29 01:53:10.260800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32fefa5b138e'
down_revision = 'ee2f4350b603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('before_after_photos',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.JSON(),
               postgresql_using='array_to_json(before_after_photos)',
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_provider_user_id', ['user_id'])
        batch_op.drop_column('availability')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('unique_booking_review', ['booking_id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('unique_booking_review', type_='unique')
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_provider_user_id', type_='unique')
        batch_op.alter_column('before_after_photos',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.TEXT()),
               postgresql_using='json_array_elements_text(before_after_photos)',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###