version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: homabay_laundry
      POSTGRES_USER: levis
      POSTGRES_PASSWORD: rabah9598
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    command: flask run --host=0.0.0.0
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://levis:rabah9598@localhost:5432/homabay_laundry
    ports:
      - '5000:5000'
    depends_on:
      - db

  client:
    build: ./client
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data: 